# Generated by Django 4.1.4 on 2023-03-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='imag',
            new_name='image',
        ),
    ]
